### ISSUE TITLE
博主你这个love 页面有点炫 能请问实现的方式吗？？

### ISSUE THREAD

**Issue by panyu97py** [nooldey/nooldey.github.io#117]
博主你这个love 页面有点炫 能请问实现的方式吗？？

**Comment by nooldey** [comment]
就是一个很流行的表白页呀，是canvas画的，我不是原作者呢😅

**Comment by panyu97py** [comment]
能请问下博主你这个页面摘自哪里嘛？或者博主你这个页面的源码？有点炫很想搞一个 。怀着求知识的心不是伸手党

**Comment by nooldey** [comment]
> 能请问下博主你这个页面摘自哪里嘛？或者博主你这个页面的源码？有点炫很想搞一个 。怀着求知识的心不是伸手党

@panyu97py 源码就是在这里：https://github.com/nooldey/nooldey.github.io/tree/master/love
